# Generated by Django 3.0.7 on 2024-04-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('measure', models.CharField(blank=True, default='', max_length=15, verbose_name='Мярка')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикули',
            },
        ),
        migrations.CreateModel(
            name='OperationTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(default=0, help_text='0 - доставка, 1 - изписване', verbose_name='Тип')),
                ('date', models.CharField(blank=True, default='', max_length=15, verbose_name='Дата')),
                ('partner1', models.TextField(blank=True, default='', verbose_name='Доставчик/Получател')),
                ('partner2', models.CharField(blank=True, default='', max_length=100, verbose_name='Приел/Предал')),
                ('doc', models.CharField(blank=True, default='', max_length=100, verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Складове',
            },
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('measure', models.CharField(blank=True, default='', max_length=15, verbose_name='Мярка')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it', to='main.Item', verbose_name='артикул')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op', to='main.OperationTitle', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Артикул от доставка/изписване',
                'verbose_name_plural': 'Артикули от доставка/изписване',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc', to='main.Stock', verbose_name='Склад'),
        ),
    ]
